stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the app"

test-job1:
  stage: test
  script:
    - echo "Testing the app"

test-job-2:
  stage: test
  script:
    - echo "Testing the app 2"

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production server"
