stages:
  - build
  - test
  - deploy

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build-job:
  stage: build
  script:
    - echo "Building the app"

test-job1:
  stage: test
  script:
    - echo "Testing the app"

test-job-2:
  stage: test
  script:
    - echo "Testing the app 2"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production server"
